"""
Django settings for gestorPro project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import psycopg2
from dotenv import load_dotenv
import os
import firebase_admin
from firebase_admin import credentials


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'controle',
    'produtos',
    'compras',
    'vendas',
    'clientes',
    'fornecedores',
    'tickets',
    'notify',
    'sslserver',
    'django_extensions',
    'fcm_django'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestorPro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestorPro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),  # Use 'localhost' or your server IP
        'PORT': os.getenv('DB_PORT'),  # Default PostgreSQL port
        'CONN_MAX_AGE': 60,
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Maceio'

USE_I18N = True

USE_TZ = True

LOGIN_URL = 'login_view'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login_view'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

SECURE_CROSS_ORIGIN_OPENER_POLICY = 'unsafe-none'

RUNSERVERPLUS_SERVER_ADDRESS_PORT = 'localhost:8000'

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.dev',
]

# 1. Define o tempo de ociosidade em segundos.
SESSION_COOKIE_AGE = 900 

# 2. ESSENCIAL: Faz o Django renovar o cronômetro a cada clique ou atualização de página.
SESSION_SAVE_EVERY_REQUEST = True

# 3. Opcional: Garante que se ele fechar o navegador, a sessão também morre.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# URL que aparecerá no navegador (ex: http://127.0.0.1:8000/media/perfis/foto.jpg)
MEDIA_URL = '/media/'

# Caminho no disco do servidor onde os arquivos realmente ficarão salvos
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# #Caminho para o arquivo JSON de credenciais
# FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'firebase-credentials.json')

# #Inicializar o App do Firebase Admin
# FIREBASE_CRED = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
# FIREBASE_APP = firebase_admin.initialize_app(FIREBASE_CRED)

# # Configurações da fcm-django
# FCM_DJANGO = {
#     "DEFAULT_FIREBASE_APP": FIREBASE_APP,
#     # Permite que o mesmo usuário receba notificações no celular e no desktop
#     "ONE_DEVICE_PER_USER": False,
#     # Exclui automaticamente tokens que o Firebase retornar como inválidos
#     "DELETE_INACTIVE_DEVICES": True,
# }